1) SELECT * FROM EMP;

2) SELECT DISTINCT JOB FROM EMP;
2) SELECT UNIQUE JOB FROM EMP;

3) SELECT * FROM EMP ORDER BY SAL ASC;

4) SELECT * FROM EMP ORDER BY DEPTNO ASC , JOB DESC;

5) SELECT DISTINCT JOB FROM EMP ORDER BY JOB DESC;

6) SELECT * FROM EMP WHERE EMPNO IN (SELECT MGR FROM EMP);

7) SELECT * FROM EMP WHERE TO_CHAR(HIREDATE, 'YYYY') < 1981;
7) SELECT * FROM EMP WHERE HIREDATE < '1-JAN-1981';

8) SELECT EMPNO, ENAME, SAL, ROUND((SAL/30),2) DAILYSAL, SAL*12 AS ANNSAL FROM EMP ORDER BY ANNSAL ASC;

9) SELECT EMPNO, ENAME, JOB, HIREDATE, ROUND(MONTHS_BETWEEN(SYSDATE,HIREDATE)) AS EXP FROM EMP WHERE EMPNO IN (SELECT MGR FROM EMP);

10) SELECT EMPNO, ENAME, SAL  FROM EMP WHERE MGR = 7369;

11) SELECT * FROM EMP WHERE COMM > SAL;

12) SELECT * FROM EMP WHERE HIREDATE > '30-JUNE-1981' AND TO_CHAR(HIREDATE, 'YYYY') = 1981 ORDER BY JOB ASC;

13) SELECT * FROM EMP WHERE (SAL/30) > 100; 

14) SELECT * FROM EMP WHERE JOB = 'CLERK' OR JOB = 'MANAGER' ORDER BY JOB DESC;
14) SELECT * FROM EMP WHERE JOB IN ('CLERK', 'MANAGER') ORDER BY JOB DESC;

15) SELECT * FROM EMP WHERE HIREDATE IN ('1-MAY-1981', '3-DEC-81', '17-DEC-80', '09-JUN-80');

16) SELECT * FROM EMP WHERE DEPTNO IN(10, 20);
16) SELECT * FROM EMP WHERE DEPTNO = 10 OR DEPTNO = 20;

17) SELECT * FROM EMP WHERE HIREDATE BETWEEN '01-JAN-1980' AND '31-DEC-1980';
17) SELECT * FROM EMP WHERE TO_CHAR(HIREDATE, 'YYYY' ) = 1981;

18) SELECT * FROM EMP WHERE TO_CHAR(HIREDATE, 'MON-YYYY') = 'AUG-1980'; 
18) SELECT * FROM EMP WHERE HIREDATE BETWEEN '1-AUG-1980' AND '31-AUG-1980'; 

19) SELECT * FROM EMP WHERE 12*SAL BETWEEN 22000 AND 45000;

20) SELECT ENAME FROM EMP WHERE ENAME LIKE '_____';
20) SELECT ENAME FROM EMP WHERE LENGTH(ENAME) = 5;

21) SELECT ENAME FROM EMP WHERE ENAME LIKE 'S____';
21) SELECT ENAME FROM EMP WHERE ENAME LIKE 'S%' AND LENGTH(ENAME) = 5;

22) SELECT ENAME FROM EMP WHERE ENAME LIKE '__R_';
22) SELECT ENAME FROM EMP WHERE ENAME LIKE '__R%' AND LENGTH(ENAME) = 4;

23) SELECT * FROM EMP WHERE ENAME LIKE 'S___H';
23) SELECT * FROM EMP WHERE ENAME LIKE 'S%H' AND LENGTH(ENAME)= 5;

24) SELECT * FROM EMP WHERE TO_CHAR(HIREDATE, 'MON') = 'JAN'; 

25) SELECT * FROM EMP WHERE TO_CHAR(HIREDATE, 'MON') LIKE '_A_';
25) SELECT * FROM EMP WHERE TO_CHAR(HIREDATE, 'MON') LIKE '_A%';

26) SELECT * FROM EMP WHERE SAL LIKE '%0' AND LENGTH(SAL)= 4;
26) SELECT * FROM EMP WHERE SAL LIKE '___0';

27) SELECT * FROM EMP WHERE ENAME LIKE '%LL%';

28) SELECT * FROM EMP WHERE TO_CHAR(HIREDATE,'YY') LIKE '8_'; 
28) SELECT * FROM EMP WHERE TO_CHAR(HIREDATE,'YY') LIKE '8%';

29) SELECT * FROM EMP WHERE DEPTNO NOT IN (20);
29) SELECT * FROM EMP WHERE DEPTNO != 20;
29) SELECT * FROM EMP WHERE DEPTNO <> 20;
29) SELECT * FROM EMP WHERE DEPTNO NOT LIKE '20';

30) SELECT * FROM EMP WHERE JOB NOT IN ('PRESIDENT', 'MANAGER') ORDER BY SAL;
30) SELECT * FROM EMP WHERE JOB NOT LIKE 'PRESIDENT' AND JOB NOT LIKE 'MANAGER' ORDER BY SAL ;

31) SELECT * FROM EMP WHERE TO_CHAR(HIREDATE, 'YYYY') <> 1981;
31) SELECT * FROM EMP WHERE TO_CHAR(HIREDATE, 'YYYY') != 1981;
31) SELECT * FROM EMP WHERE TO_CHAR(HIREDATE, 'YYYY') NOT IN (1981);
31) SELECT * FROM EMP WHERE TO_CHAR(HIREDATE, 'YYYY') NOT LIKE '1981';

32) SELECT * FROM EMP WHERE EMPNO NOT LIKE '78%';

33) SELECT E.ENAME||' WORKS FOR '|| M.ENAME 
FROM EMP E, EMP M 
WHERE E.MGR = M.
EMPNO;

33) SELECT E.ENAME|| ' HAS EMPLOYEE '|| M.ENAME
FROM EMP E, EMP M
WHERE E.EMPNO = M.MGR;

34) SELECT * FROM EMP WHERE TO_CHAR(HIREDATE,'MON') NOT IN ('MAR');
SELECT * FROM EMP WHERE TO_CHAR(HIREDATE,'MON') NOT LIKE 'MAR';
SELECT * FROM EMP WHERE TO_CHAR(HIREDATE,'MON') <> 'MAR';
SELECT * FROM EMP WHERE TO_CHAR(HIREDATE,'MON') != 'MAR';

35) SELECT * FROM EMP WHERE JOB = 'CLERK' AND DEPTNO = 20;

36) SELECT * FROM EMP WHERE TO_CHAR(HIREDATE, 'YYYY') = '1981' AND DEPTNO IN (10, 30);
SELECT * FROM EMP WHERE TO_CHAR(HIREDATE, 'YYYY') LIKE '1981' AND DEPTNO IN (10, 30);
SELECT * FROM EMP WHERE TO_CHAR(HIREDATE, 'YYYY') LIKE '1981' AND (DEPTNO = 10 OR DEPTNO = 30);
SELECT * FROM EMP WHERE TO_CHAR(HIREDATE, 'YYYY')= '1981' AND (DEPTNO = 10 OR DEPTNO = 30);
SELECT * FROM EMP WHERE TO_CHAR(HIREDATE, 'YYYY') IN (1981) AND (DEPTNO = 10 OR DEPTNO = 30);
SELECT * FROM EMP WHERE TO_CHAR(HIREDATE, 'YYYY') IN (1981) AND DEPTNO IN (10, 30);

37) SELECT * FROM EMP WHERE ENAME = 'SMITH';
38) SELECT D.LOC 
FROM EMP E, DEPT D
WHERE ENAME = 'SMITH' AND E.DEPTNO = D.DEPTNO;

39) SELECT * FROM EMP E, DEPT D 
WHERE E.DEPTNO = D.DEPTNO AND D.DNAME IN ('ACCOUNTING', 'RESEARCH')
ORDER BY E.DEPTNO ASC;

40 )(RECOMMENDED BECAUSE MLTIPLE MULTIROW SUBQUERY) SELECT E.EMPNO, E.ENAME, E.SAL, D.DNAME FROM EMP E , DEPT D
WHERE E.DEPTNO = D.DEPTNO
AND D.LOC IN ('NEW YORK', 'DALLAS')
AND EMPNO IN ( SELECT E.EMPNO FROM EMP E
                WHERE E.JOB IN ('MANAGER', 'ANALYST')
                AND (MONTHS_BETWEEN(SYSDATE,E.HIREDATE)/12) > 7
                AND E.COMM IS NULL 
            ) 
ORDER BY D.LOC ASC ;

40) SELECT E.EMPNO, E.ENAME, E.SAL, D.DNAME FROM EMP E , DEPT D
WHERE E.DEPTNO = D.DEPTNO
AND D.LOC IN ('NEW YORK', 'DALLAS')
AND E.JOB IN ('MANAGER', 'ANALYST')
AND (MONTHS_BETWEEN(SYSDATE,E.HIREDATE)/12) > 7
AND E.COMM IS NULL             
ORDER BY D.LOC ASC ;
---------------------------

41) SELECT E.EMPNO, E.ENAME, E.SAL, D.DNAME, D.LOC, D.DEPTNO, E.JOB FROM EMP E, DEPT D
WHERE (D.LOC = 'CHICAGO' OR D.DNAME = 'ACCOUNTING')
AND E.DEPTNO= D.DEPTNO
AND  E.SAL*12 > 28000 
AND E.SAL NOT IN (3000, 2800) 
AND JOB != 'MANAGER'
AND (E.EMPNO NOT LIKE '__7%' OR E.EMPNO NOT LIKE '__8%') 
ORDER BY D.DEPTNO ASC, E.JOB DESC;

41) //CALCULATE ALL FROM 2ND TABLE DEPT AND JOIN 1ST EMP USING SUBQUERY
SELECT E.EMPNO, E.ENAME, E.SAL, D.DNAME, D.LOC, D.DEPTNO, E.JOB FROM EMP E, DEPT D
WHERE (D.LOC = 'CHICAGO' OR D.DNAME = 'ACCOUNTING')
AND E.DEPTNO= D.DEPTNO
AND EMPNO IN (
                SELECT E.EMPNO FROM EMP E 
                WHERE (E.SAL*12) > 28000 
                AND E.SAL NOT IN (3000, 2800) 
                AND E.JOB != 'MANAGER'
                AND ( E.EMPNO NOT LIKE '__7%' OR E.EMPNO NOT LIKE '__8%') 
            )
ORDER BY D.DEPTNO ASC, E.JOB DESC;


42) SELECT * FROM EMP E, SALGRADE S
WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
ORDER BY S.GRADE ASC;

42)
SELECT * FROM EMP E, SALGRADE S
WHERE E.SAL >= S.LOSAL AND E.SAL<=HISAL
ORDER BY S.GRADE ASC;

43) //CALCULATE ALL FROM 2ND TABLE SAGRADE AND JOIN 1ST EMP USING SUBQUERY
SELECT * FROM EMP E, SALGRADE S
WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL 
AND S.GRADE IN (4,5) 
AND EMPNO IN (SELECT EMPNO FROM EMP E WHERE JOB IN ('MANAGER', 'ANALYST'));

43) SELECT EMPNO, ENAME, SAL, DNAME, GRADE, ROUND(MONTHS_BETWEEN(SYSDATE, E.HIREDATE)/12) AS EXP, (12*SAL) AS ANNSAL FROM EMP E, DEPT D, SALGRADE S
WHERE D.DEPTNO IN (10, 20)
AND E.DEPTNO = D.DEPTNO
AND E.SAL BETWEEN S.LOSAL AND S.HISAL;



44) SELECT E.EMPNO, E.ENAME, D.DNAME, D.LOC, E.SAL, S.GRADE FROM EMP E, DEPT D, SALGRADE S
WHERE E.DEPTNO = D.DEPTNO
AND (DNAME NOT LIKE 'OP%' AND DNAME NOT LIKE '%S')
AND E.SAL BETWEEN S.LOSAL AND S.HISAL AND S.GRADE IN (2, 3, 4) 
AND EMPNO IN ( SELECT EMPNO FROM EMP 
                WHERE JOB LIKE '%A%' 
                AND TO_CHAR(HIREDATE, 'YYYY') = 1981 
                AND TO_CHAR(HIREDATE, 'MON') NOT IN ('MAR', 'SEP')
                AND SAL NOT LIKE '%00'
            )
ORDER BY GRADE ASC;

47) SELECT * FROM EMP E, DEPT D
WHERE E.DEPTNO(+) = D.DEPTNO;

48) SELECT * FROM EMP WHERE SAL > (SELECT SAL FROM EMP WHERE ENAME = 'BLAKE');

49) SELECT * FROM EMP WHERE JOB = (SELECT JOB FROM EMP WHERE ENAME= 'ALLEN');

50) SELECT * FROM EMP WHERE HIREDATE < (SELECT HIREDATE FROM EMP WHERE ENAME = 'KING');


51) --SELECT X.ENAME||' HAS MANAGER '||Y.ENAME FROM EMP X, EMP Y
SELECT * FROM EMP X, EMP Y
WHERE X.MGR = Y.EMPNO;
AND X.HIREDATE < Y.HIREDATE;

51) --SELECT X.ENAME ||' WORKS UNDER '||Y.ENAME FROM EMP X, EMP Y
SELECT * FROM EMP X, EMP Y
WHERE X.EMPNO = Y.MGR;
AND X.HIREDATE > Y.HIREDATE;

52) SELECT * FROM EMP E, DEPT D 
WHERE E.DEPTNO = D.DEPTNO
AND D.DEPTNO = 20
AND E.JOB IN (SELECT E.JOB FROM EMP E , DEPT D
            WHERE E.DEPTNO = D.DEPTNO
            AND D.DEPTNO = 10);

52) SELECT * FROM EMP E, DEPT D 
WHERE E.DEPTNO = D.DEPTNO
AND D.DEPTNO = 20
AND E.JOB IN (SELECT E.JOB FROM EMP E 
            WHERE E.DEPTNO = 10);
            
            
53) SELECT * FROM EMP E 
WHERE E.SAL IN (SELECT E.SAL FROM EMP E WHERE E. ENAME IN ('SMITH', 'FORD'))
ORDER BY SAL DESC;            

54) SELECT * FROM EMP E
WHERE E.JOB IN ( SELECT E.JOB FROM EMP E WHERE E.ENAME = 'MILLER')
    OR E.SAL > (SELECT E.SAL FROM EMP WHERE ENAME = 'ALLEN');
               
55) SELECT * FROM EMP
WHERE SAL < (SELECT SUM(NVL2(COMM, SAL+COMM, SAL))
                FROM EMP WHERE JOB = 'SALESMAN');
56) SELECT * FROM EMP E, DEPT D
WHERE D.LOC IN ('CHICAGO', 'BOSTON')
AND E.DEPTNO = D.DEPTNO
AND E.HIREDATE < (SELECT E.HIREDATE FROM EMP E WHERE E.ENAME = 'BLAKE');

57) SELECT * FROM EMP E
WHERE E.DEPTNO IN (SELECT D.DEPTNO FROM DEPT D
                WHERE D.DNAME IN ('ACCOUNTING', 'RESEARCH'))
AND E.SAL > (SELECT E.SAL FROM EMP E WHERE E.ENAME = 'ALLEN')
AND E.HIREDATE <(SELECT E.HIREDATE FROM EMP E WHERE E.ENAME = 'SMITH')
AND E.EMPNO IN (SELECT E.EMPNO FROM EMP E, SALGRADE S 
                WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL AND S.GRADE IN (3,4))
ORDER BY E.HIREDATE DESC;


58) SELECT * FROM EMP WHERE JOB IN (SELECT JOB FROM EMP WHERE ENAME IN ('SMITH', 'ALLEN'));

59 a) SELECT SAL FROM EMP;

   SELECT * FROM EMP E WHERE E.SAL IN (SELECT B.SAL*(3/4) FROM EMP B WHERE E.MGR = B.EMPNO);
    
    SELECT * FROM EMP E WHERE E.SAL IN (SELECT B.SAL*(3/4) FROM EMP E, EMP B
    WHERE E.MGR = B.EMPNO);
    
60) SELECT E.JOB, E.DEPTNO FROM EMP E WHERE E.JOB NOT IN (SELECT B.JOB FROM EMP B WHERE E.DEPTNO = 20) 
AND
E.DEPTNO = 10;

61)
62) SELECT MAX(SAL) FROM EMP;

63) SELECT * FROM EMP WHERE SAL = (SELECT MAX(SAL) FROM EMP);
63) SELECT * FROM EMP WHERE SAL IN (SELECT MAX(SAL) FROM EMP);

64) 
---- USING SUBQUERY
    SELECT * FROM EMP WHERE SAL IN (SELECT MAX(SAL) FROM EMP WHERE DEPTNO IN (SELECT DEPTNO FROM DEPT WHERE DNAME = 'SALES')); 
    
------USING JOIN CONDITION
    SELECT * FROM EMP E, DEPT D
    WHERE E.DEPTNO = D.DEPTNO
    AND E.SAL IN(SELECT MAX(SAL) FROM EMP
                    WHERE DEPTNO IN (SELECT DEPTNO FROM DEPT
                                    WHERE DNAME ='SALES')
                );

    
65) SELECT * FROM EMP E WHERE E.DEPTNO IN (SELECT D.DEPTNO FROM DEPT D WHERE D.LOC = 'DALLAS')
AND E.HIREDATE IN ( SELECT MAX(E.HIREDATE) FROM EMP E 
                    WHERE EMPNO IN (SELECT E.EMPNO FROM EMP E, SALGRADE S 
                                    WHERE S.GRADE = 4 AND E.SAL BETWEEN S.LOSAL AND S.HISAL));


66) SELECT * FROM EMP 
    WHERE HIREDATE < (SELECT MAX(HIREDATE) FROM EMP 
                                        WHERE MGR IN (SELECT EMPNO FROM EMP 
                                                      WHERE ENAME = 'KING'));

67) SELECT * FROM EMP E
WHERE E.DEPTNO IN (SELECT D.DEPTNO FROM DEPT D 
                   WHERE D.LOC = 'NEW YORK')
AND E.EMPNO IN (SELECT E.EMPNO FROM EMP E, SALGRADE S WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL AND S.GRADE IN (3,4,5))
AND E.JOB NOT IN ('PRESIDENT') 
AND E.SAL > (SELECT MAX(E.SAL) FROM EMP E WHERE E.DEPTNO IN (SELECT D.DEPTNO FROM DEPT D WHERE D.LOC = 'CHICAGO')
AND JOB IN ('MANAGER', 'SALESMAN')
AND E.MGR NOT IN (SELECT EMPNO FROM EMP WHERE ENAME = 'KING'));



68) SELECT * FROM EMP WHERE HIREDATE IN (SELECT MIN(HIREDATE) FROM EMP WHERE TO_CHAR(HIREDATE, 'YYYY') = 1981);


69) SELECT * FROM EMP 
WHERE TO_CHAR(HIREDATE, 'YYYY') = 1981 
AND JOB IN (SELECT JOB FROM EMP 
            WHERE HIREDATE IN (SELECT MIN(HIREDATE) FROM EMP 
                               WHERE TO_CHAR(HIREDATE, 'YYYY') = 1981));


70) SELECT * FROM EMP
    WHERE HIREDATE IN (SELECT MIN(HIREDATE) FROM EMP
                        WHERE MGR IN (SELECT EMPNO FROM EMP 
                                      WHERE ENAME = 'KING'))
    AND EMPNO IN (SELECT E.EMPNO FROM EMP E, SALGRADE S
                 WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL AND S.GRADE > 3);

71) SELECT SUM(E.SAL) AS TOTSAL FROM EMP E WHERE E.JOB = 'MANAGER';
71) SELECT SUM(SAL) FROM EMP WHERE EMPNO IN (SELECT EMPNO FROM EMP WHERE JOB = 'MANAGER');

72) SELECT JOB, SUM(SAL*12) AS ANNSAL FROM EMP
WHERE TO_CHAR(HIREDATE, 'YYYY') = 1981
GROUP BY JOB ;

73) SELECT SUM(SAL) FROM EMP WHERE EMPNO IN (SELECT EMPNO FROM EMP, SALGRADE S WHERE SAL BETWEEN S.LOSAL AND S.HISAL AND S.GRADE = 3);

74) SELECT AVG(SAL) FROM EMP WHERE JOB = 'CLERK' ;
                                                        
75) SELECT * FROM EMP WHERE DEPTNO = 20 
AND SAL > (SELECT AVG(SAL) FROM EMP WHERE DEPTNO = 10);

76) SELECT DEPTNO, JOB, COUNT(*) FROM EMP GROUP BY DEPTNO, JOB;

76) SELECT D.DEPTNO, E.JOB, COUNT(E.JOB) FROM EMP E , DEPT D
WHERE E.DEPTNO (+)= D.DEPTNO GROUP BY D.DEPTNO, E.JOB;

77) SELECT E.MGR, COUNT(*) FROM EMP E, EMP M 
WHERE E.MGR = M.MGR GROUP BY E.MGR ORDER BY E.MGR;

78) SELECT DEPTNO, COUNT(*) FROM EMP GROUP BY DEPTNO HAVING COUNT(*)>2;

79) SELECT GRADE , COUNT(EMPNO), MAX(SAL) FROM EMP E, SALGRADE S
WHERE SAL BETWEEN LOSAL AND HISAL GROUP BY GRADE ;

80) SELECT DNAME, GRADE, COUNT(*) FROM EMP E, DEPT D, SALGRADE S
WHERE E.DEPTNO = D.DEPTNO 
AND E.JOB = 'CLERK'
AND E.SAL BETWEEN S.LOSAL AND S.HISAL GROUP BY D.DNAME, S.GRADE HAVING COUNT(*)>=2;


81) SELECT * FROM DEPT WHERE DEPTNO IN (SELECT DEPTNO FROM EMP 
                                    GROUP BY DEPTNO 
                                    HAVING COUNT(*)=(SELECT MAX(COUNT(*)) FROM EMP GROUP BY DEPTNO) );

81) SELECT E.DEPTNO, D.DNAME, D.LOC, COUNT(*) FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO
GROUP BY E.DEPTNO, D.DNAME, D.LOC HAVING COUNT(*)=(SELECT MAX(COUNT(*)) FROM EMP GROUP BY DEPTNO);


82) 
SELECT * FROM EMP WHERE MGR = (SELECT EMPNO FROM EMP WHERE ENAME = 'JONES' );
SELECT * FROM EMP WHERE MGR IN (SELECT EMPNO FROM EMP WHERE ENAME = 'JONES' );

83) SELECT * FROM EMP WHERE (SAL*1.2) > 3000;

84) SELECT E.EMPNO, E.ENAME, E.SAL, D.DNAME, D.LOC FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO;
GROUP BY D.DNAME;

85) SELECT * FROM EMP E, DEPT D 
WHERE E.DEPTNO = D.DEPTNO
AND D.DNAME NOT IN ('SALES');

85) SELECT * FROM EMP WHERE DEPTNO IN (SELECT DEPTNO FROM DEPT WHERE DNAME NOT IN ('SALES'));

86) SELECT E.ENAME, E.DEPTNO, E.SAL, E.COMM FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO 
AND E.SAL BETWEEN 2000 AND 5000 AND D.LOC = 'CHICAGO'; 

87) SELECT * FROM EMP W, EMP M
WHERE W.MGR = M.MGR
AND W.SAL > M.SAL;

88) SELECT S.GRADE, E.ENAME FROM EMP E, DEPT D, SALGRADE S
WHERE E.DEPTNO = D.DEPTNO
AND E.SAL BETWEEN S.LOSAL AND S.HISAL AND GRADE NOT IN (4)
AND D.DEPTNO IN (10, 30)
AND HIREDATE < ('31-DEC-1982');

89) SELECT E.ENAME, E.JOB, D.DNAME, D.LOC FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO
AND E.MGR IN (SELECT G.EMPNO FROM EMP G);

90) SELECT *  FROM EMP M, EMP N
WHERE M.MGR = N.EMPNO 
AND N.ENAME = 'JONES';

90) SELECT * FROM EMP E
WHERE E.MGR IN (SELECT K.EMPNO FROM EMP K WHERE K.ENAME = 'JONES');

91) SELECT E.ENAME, E.SAL FROM EMP E, SALGRADE S
WHERE E.ENAME = 'FORD'
AND E.SAL BETWEEN S.LOSAL AND S.HISAL
AND E.SAL = S.HISAL;

92) SELECT E.ENAME, E.JOB, E.SAL, E.DEPTNO, S.GRADE FROM EMP E, DEPT D, SALGRADE S
WHERE E.DEPTNO = D.DEPTNO
AND E.SAL BETWEEN S.LOSAL AND S.HISAL
GROUP BY E.DEPTNO, E.ENAME, E.JOB, E.SAL, S.GRADE
ORDER BY DEPTNO;


93) SELECT E.ENAME, E.JOB, E.SAL, S.GRADE, D.DNAME FROM EMP E, DEPT D,SALGRADE S
WHERE E.DEPTNO = D.DEPTNO
AND E.SAL BETWEEN S.LOSAL AND S.HISAL
AND E.JOB NOT IN ('CLERK')
ORDER BY E.SAL DESC;

94) SELECT E.ENAME, E.JOB FROM EMP E WHERE E.MGR IS NULL;

95) SELECT * FROM EMP E WHERE E.SAL IN (SELECT MAX(SAL) FROM EMP) ORDER BY DEPTNO;

96) SELECT * FROM EMP E WHERE E.SAL = ( SELECT (MIN(E.SAL) + MAX(E.SAL))/2 AS AVG FROM EMP );

97) SELECT E.DEPTNO, COUNT(*) FROM EMP E, DEPT D 
GROUP BY E.DEPTNO HAVING COUNT(*) > 3;

98) SELECT D.DNAME, COUNT(*) FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO
GROUP BY D.DNAME
HAVING COUNT(*) <= 3;

99) SELECT * FROM EMP E 
WHERE E.EMPNO IN (SELECT MGR FROM EMP)
AND E.SAL > (SELECT AVG(M.SAL) FROM EMP M 
            WHERE E.MGR = M.EMPNO );

100) 
SELECT ENAME, SAL, NETSAL FROM (SELECT ENAME, SAL, SAL+NVL(COMM, 0) AS NETSAL FROM EMP ) 
WHERE NETSAL >= SAL;

100)
SELECT E.ENAME, E.SAL, E.COMM FROM EMP E 
WHERE SAL + NVL(E.COMM, 0) >= ANY (SELECT E.SAL FROM EMP);

100) 
SELECT E.ENAME, E.SAL, E.COMM FROM EMP E
WHERE NVL2(E.COMM, E.SAL+E.COMM, E.SAL) >= ANY (SELECT SAL FROM EMP);

101) 
SELECT * FROM EMP E, EMP M 
WHERE E.MGR = M.EMPNO
AND E.SAL < M.SAL
AND E.SAL >ANY (SELECT SAL FROM EMP WHERE EMPNO IN (SELECT MGR FROM EMP)); 

101) 
SELECT E.EMPNO, E.ENAME, E.SAL FROM(SELECT E.EMPNO, E.ENAME, E.SAL FROM EMP E, EMP M WHERE E.MGR = M.EMPNO) E, (SELECT * FROM EMP WHERE EMPNO IN (SELECT MGR FROM EMP)) A 
WHERE E.SAL > A.SAL;

102)
SELECT E.DEPTNO, E.ENAME, ROUND(AVG(NVL2(E.COMM, E.SAL+E.COMM, E.SAL))) AVG, M.ENAME FROM EMP E, EMP M, DEPT D
WHERE E.DEPTNO = D.DEPTNO AND M.DEPTNO = D.DEPTNO
GROUP BY E.DEPTNO, E.ENAME, M.ENAME;

------SELECT E.ENAME, E.DEPTNO, D.MAXSAL AS 'CURRENTSAL' FROM EMP E, 
--(SELECT AVG(SAL) AS MAXSAL, DEPTNO FROM EMP GROUP BY DEPTNO) D
--WHERE E.DEPTNO = D.DEPTNO;--

103) 
SELECT * FROM EMP E WHERE 5 > (SELECT COUNT(*) FROM EMP WHERE E.SAL > SAL) ORDER BY SAL DESC;
SELECT * FROM EMP E WHERE 5 > (SELECT COUNT(DISTINCT SAL) FROM EMP WHERE E.SAL > SAL) ORDER BY SAL DESC;

104)
SELECT * FROM EMP E , (SELECT * FROM EMP WHERE EMPNO IN (SELECT MGR FROM EMP)) M
WHERE E.SAL > M.SAL;

104)
SELECT * FROM EMP E, EMP K
WHERE E.MGR = K.EMPNO
AND E.SAL > K.SAL;

105) 
SELECT * FROM EMP WHERE EMPNO IN (SELECT MGR FROM EMP) 
                  AND MGR IN ( SELECT EMPNO FROM EMP WHERE JOB <> 'PRESIDENT');
105) 
SELECT * FROM EMP WHERE EMPNO IN (SELECT MGR FROM EMP)
                AND MGR NOT IN (SELECT EMPNO FROM EMP WHERE JOB = 'PRESIDENT');

106)

107)
SELECT E.ENAME, E.SAL, E.COMM, NVL2(E.COMM,E.SAL+E.COMM, E.SAL) AS NETPAY FROM EMP E
WHERE NVL2(COMM,E.SAL+E.COMM, E.SAL) > ANY (SELECT E.SAL FROM EMP);

108)
SELECT * FROM EMP WHERE ADD_MONTHS(HIREDATE, 240) > '31-DEC-89';
SELECT * FROM EMP WHERE ADD_MONTHS(HIREDATE, 96)> TO_DATE('31-DEC-89', 'DD-MON-RR');

109)
SELECT SAL FROM EMP WHERE MOD(SAL, 2) = 1; 

110)
SELECT * FROM EMP WHERE SAL LIKE '___';

111)
SELECT * FROM EMP WHERE TO_CHAR(HIREDATE, 'MON') IN ('DEC');
SELECT  *FROM EMP WHERE TO_CHAR(HIREDATE, 'MONTH') LIKE 'DEC%';

112)
SELECT * FROM EMP WHERE ENAME LIKE '%A%';

113)
SELECT * FROM EMP WHERE INSTR(SAL, DEPTNO)>0;

114)
SELECT * FROM EMP 
WHERE SUBSTR(HIREDATE,1,2) = SUBSTR(SAL, LENGTH(SAL)-1, LENGTH(SAL));

115)
SELECT * FROM EMP 
WHERE TO_CHAR(HIREDATE, 'YY') IN (SELECT 0.1*SAL FROM EMP);

116)
SELECT LOWER(SUBSTR(ENAME, 1, ROUND(LENGTH(ENAME)/2))) || SUBSTR(ENAME, ROUND(LENGTH(ENAME)/2)+1, LENGTH(ENAME)) FROM EMP;

117)
SELECT * FROM DEPT D WHERE LENGTH(D.DNAME) <ANY (SELECT COUNT(*) FROM EMP E, DEPT D 
                                                WHERE E.DEPTNO = D.DEPTNO);
117)                                        
SELECT DNAME, COUNT(*) FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO 
GROUP BY DNAME
HAVING COUNT(*) < LENGTH(DNAME);

118) 
SELECT * FROM EMP 
WHERE TO_CHAR(HIREDATE, 'DD') < 15;

119)
SELECT * FROM DEPT D 
WHERE LENGTH(D.DNAME) IN (SELECT COUNT(*) FROM EMP
                          WHERE D.DEPTNO <> DEPTNO 
                          GROUP BY DEPTNO);

SELECT * FROM DEPT D 
WHERE LENGTH(D.DNAME) = ANY (SELECT COUNT(*) FROM EMP WHERE D.DEPTNO <> DEPTNO GROUP BY DEPTNO);


SELECT * FROM DEPT D, (SELECT COUNT(*) K , E.DEPTNO G FROM EMP E GROUP BY E.DEPTNO) D1
WHERE LENGTH(D.DNAME) = D1.K
AND D.DEPTNO <> D1.G;

120)
SELECT * FROM EMP WHERE JOB = 'MANAGER';

SELECT * FROM EMP WHERE EMPNO IN (SELECT MGR FROM EMP);

121)
SELECT D.DNAME FROM DEPT D
WHERE D.DEPTNO IN (SELECT E.DEPTNO FROM EMP E
                    GROUP BY E.DEPTNO
                    HAVING COUNT(*) IN (SELECT MAX(COUNT(*)) FROM EMP GROUP BY DEPTNO) 
                );
                
122)
SELECT COUNT(*) FROM ( SELECT * FROM EMP MINUS SELECT * FROM EMP WHERE JOB <> 'MANAGER');
SELECT COUNT(*) FROM EMP WHERE EMPNO IN ( SELECT EMPNO FROM EMP WHERE JOB = 'MANAGER');

123)
SELECT * FROM EMP E WHERE HIREDATE IN (SELECT HIREDATE FROM EMP WHERE E.EMPNO <> EMPNO);

124)
SELECT * FROM EMP E, SALGRADE S
WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
AND S.GRADE = 0.1* (SELECT DEPTNO FROM DEPT WHERE DNAME = 'SALES');

SELECT D.DNAME FROM DEPT D, EMP E WHERE E.DEPTNO = D.DEPTNO
GROUP BY D.DNAME
HAVING COUNT(*) > (SELECT AVG(COUNT(*)) FROM EMP GROUP BY DEPTNO); 

125) 
SELECT D.DNAME FROM DEPT D, EMP E
WHERE E.DEPTNO = D.DEPTNO
GROUP BY D.DNAME
HAVING COUNT(*) > (SELECT AVG(COUNT(*)) FROM EMP GROUP BY DEPTNO);

126)
SELECT M.ENAME, COUNT(*) FROM EMP E, EMP M 
WHERE E.MGR = M.EMPNO
GROUP BY M.ENAME
HAVING COUNT(*) = (SELECT MAX(COUNT(*)) FROM EMP GROUP BY MGR);

SELECT * FROM EMP WHERE EMPNO = (SELECT MGR FROM EMP
                                GROUP BY MGR 
                                HAVING COUNT(*) = (SELECT MAX(COUNT(*)) FROM EMP GROUP BY MGR)
                                ) ;
127)
SELECT ENAME, TO_CHAR(1.15*SAL, '$99,999') FROM EMP;
SELECT ENAME, '$'||(1.15*SAL) SAL FROM EMP;

128)
SELECT ENAME||JOB AS "EMP_AND_JOB" FROM EMP;
SELECT ENAME||JOB EMP_AND_JOB FROM EMP;

129)
SELECT ENAME||'('||LOWER(JOB)||')' EMPLOYEE FROM EMP;

130)
SELECT EMPNO, ENAME, SAL, TO_CHAR(HIREDATE, 'MONTH DD, YYYY') FROM EMP;

131)
SELECT EMPNO, ENAME, SAL||' JUST SALARY' "SAL" FROM EMP WHERE SAL > 1500
UNION 
SELECT EMPNO, ENAME, SAL||' ON TARGET' "SAL" FROM EMP WHERE SAL = 1500
UNION
SELECT EMPNO, ENAME, SAL ||' BELOW 1500' "SAL" FROM EMP WHERE SAL < 1500;


SELECT EMPNO, ENAME, SAL,
CASE 
WHEN SAL > 1500 THEN ' ABOVE 1500'
WHEN SAL = 1500 THEN ' ON TARGET'
WHEN SAL < 1500 THEN ' BELOW 1500'
ELSE 'NOTHING'
END AS RESULT1
FROM EMP;

132)
SELECT TO_CHAR(TO_DATE('&S', 'DD-MM-YY'), 'DAY') DAY FROM DUAL;

139)
SELECT DISTINCT  M.ENAME, M.SAL FROM EMP E, EMP M
WHERE E.MGR = M.EMPNO
AND E.SAL > M.SAL;

SELECT E.ENAME, E.SAL FROM EMP E
WHERE E.EMPNO IN (SELECT M.MGR FROM EMP M WHERE M.SAL > E.SAL);

SELECT * FROM EMP E 
WHERE E.EMPNO IN (SELECT MGR FROM EMP WHERE SAL > E.SAL);

140)
SELECT * FROM EMP WHERE MGR IN (SELECT EMPNO FROM EMP WHERE ENAME = 'BLAKE');

141)
SELECT * FROM EMP WHERE EMPNO IN (SELECT MGR FROM EMP); --CORELATED SUBQUERY

142)
SELECT E.ENAME, M.ENAME, (SELECT ENAME FROM EMP WHERE M.MGR = EMPNO)"HIS MANAGER"
FROM EMP E, EMP M 
WHERE E.MGR = M.EMPNO
AND M.ENAME = 'JONES';

SELECT E.ENAME, W.ENAME, M.ENAME 
FROM EMP E, EMP W, EMP M
WHERE E.MGR = W.EMPNO
AND W.ENAME = 'JONES'
AND W.MGR = M.EMPNO;

144) 
SELECT COUNT(*) FROM EMP WHERE JOB = 'MANAGER';
SELECT COUNT(*) TOTAL FROM EMP WHERE EMPNO IN (SELECT MGR FROM EMP);
SELECT COUNT(DISTINCT M.EMPNO) TOTAL  FROM EMP E, EMP M WHERE E.MGR = M.EMPNO; 

145)
SELECT ROUND(AVG(SAL),2) AVG_SAL, ROUND(AVG(SAL+NVL(COMM, 0)),2) AVG_RENUM FROM EMP;

146)
SELECT UNIQUE EMPNO FROM EMP ;

147)
SELECT * FROM EMP WHERE SAL < 1000 ORDER BY SAL DESC;

148)
SELECT E.ENAME, E.JOB, SAL*12 ANNSAL, D.DEPTNO, D.DNAME, S.GRADE
FROM EMP E, DEPT D, SALGRADE S
WHERE E.DEPTNO = D.DEPTNO
AND E.SAL BETWEEN S.LOSAL AND S.HISAL
AND (((E.SAL*12) = 36000) OR (E.JOB <> 'CLERK'));

149)
SELECT * FROM EMP 
WHERE (TO_CHAR(HIREDATE, 'MM') <= 06 AND TO_CHAR(HIREDATE, 'YYYY') = 1984)
AND 
JOB IN (SELECT JOB FROM EMP WHERE TO_CHAR(HIREDATE, 'MM') <= 06 AND TO_CHAR(HIREDATE, 'YYYY') = 1983);
                    
150)
SELECT * FROM EMP E, EMP M 
WHERE E.MGR = M.EMPNO
AND E.HIREDATE < M.HIREDATE;

151)
SELECT * FROM EMP E WHERE E.HIREDATE < (SELECT HIREDATE FROM EMP WHERE EMPNO = E.MGR);

152)
SELECT * FROM EMP WHERE SAL IN (SELECT MIN(SAL) FROM EMP GROUP BY JOB)
ORDER BY SAL ASC ;

153)
SELECT * FROM EMP WHERE SAL IN (SELECT MAX(SAL) FROM EMP GROUP BY JOB )
ORDER BY SAL DESC;

154)
SELECT * FROM EMP E
WHERE HIREDATE IN (SELECT MAX(HIRE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              DATE) FROM EMP WHERE E.DEPTNO = DEPTNO) 
ORDER BY HIREDATE DESC; 

SELECT * FROM EMP E
WHERE E.DEPTNO = DEPTNO
AND E.HIREDATE IN (SELECT MAX(HIREDATE) FROM EMP 
                    WHERE E.DEPTNO = DEPTNO GROUP BY DEPTNO) 
ORDER BY SAL DESC;

155)
SELECT E.ENAME, E.SAL FROM EMP E, DEPT D
WHERE E.SAL > (SELECT AVG(SAL) FROM EMP WHERE E.DEPTNO = DEPTNO) 
ORDER BY D.DEPTNO;

SELECT E.ENAME, E.SAL, E.DEPTNO FROM EMP E, (SELECT AVG(SAL) A, DEPTNO D FROM EMP GROUP BY DEPTNO) K
WHERE K.D = E.DEPTNO
AND E.SAL > K.A;

156)
SELECT DEPTNO , COUNT(*) FROM EMP 
GROUP BY DEPTNO
HAVING COUNT(*) = 0;

157)
SELECT COUNT(*), AVG(SAL), DEPTNO, JOB FROM EMP 
GROUP BY DEPTNO, JOB;

158)
SELECT MAX(AVG(SAL)) FROM EMP
WHERE JOB <> 'PRESIDENT' 
GROUP BY JOB;

159)
SELECT E.ENAME, E.JOB , E.COMM , SAL , MAX(SAL) FROM EMP E
WHERE SAL = (SELECT MAX(SAL) FROM EMP) 
AND E.COMM IS NOT NULL
GROUP BY  E.ENAME, E.JOB , E.COMM , E.SAL;

160)
SELECT ENAME, JOB, SAL , DEPTNO FROM EMP 
WHERE DEPTNO <> 20
AND JOB IN (SELECT JOB FROM EMP WHERE DEPTNO = 10)
AND SAL IN (SELECT SAL FROM EMP WHERE DEPTNO = 10);

SELECT ENAME, JOB, SAL, DEPTNO FROM EMP 
WHERE DEPTNO <> 10
AND (JOB, SAL) IN (SELECT JOB, SAL FROM EMP WHERE DEPTNO = 10);

161)
SELECT E.DEPTNO, E.ENAME, E.JOB, E.SAL,(SAL+NVL(COMM,0)) FROM EMP E
WHERE JOB = 'SALESMAN'
AND E.SAL IN (SELECT MAX(SAL) FROM EMP 
                WHERE COMM IS NOT NULL) 
ORDER BY COMM DESC;

162)
SELECT E.DEPTNO, E.ENAME, E.JOB, E.SAL, (E.SAL+NVL(E.COMM,0)) FROM EMP E
WHERE 1 = (SELECT COUNT(DISTINCT SAL) FROM EMP 
            WHERE SAL+NVL(COMM,0) > (E.SAL+NVL(E.COMM, 0)));


SELECT E.ENAME, E.SAL FROM EMP E 
WHERE 1 = (SELECT COUNT(DISTINCT SAL) FROM EMP
            WHERE SAL > E.SAL);
0 = FIRST
1 = SECOND
2 = THIRD
3 = FOURTH
.
.

163)
SELECT DEPTNO, ROUND(AVG(SAL),2) FROM EMP
GROUP BY DEPTNO
HAVING AVG(SAL) < (SELECT AVG(SAL) FROM EMP);

164)
SELECT E.ENAME, E.SAL, M.ENAME MGR, M.SAL MGR_SAL FROM EMP E, EMP M
WHERE E.MGR = M.EMPNO
AND E.SAL > M.SAL;

165)
-----DEPT WISE MAX(AVG(SAL))
SELECT * FROM EMP WHERE DEPTNO IN (SELECT DEPTNO FROM EMP GROUP BY DEPTNO
                                    HAVING AVG(SAL) = (SELECT MAX(AVG(SAL)) FROM EMP GROUP BY DEPTNO) );


---MAX(AVG(SAL))
SELECT E.ENAME, E.JOB, E.SAL FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO 
GROUP BY E.ENAME, E.JOB, E.SAL
HAVING AVG(SAL)= (SELECT MAX(AVG(SAL)) FROM EMP GROUP BY ENAME, JOB, SAL);

SELECT * FROM EMP;





CL SCR;
SELECT * FROM EMP;
SELECT * FROM DEPT;
SELECT * FROM SALGRADE;









